### ISSUE TITLE
initial project setup 

### ISSUE THREAD

**Issue by J-Raymer** [J-Raymer/printlink3d#1]
create initial project structure for front end. (React)

**Comment by DH3773** [comment]
We've chosen Javascript (typescript) and Bootstrap for the front end, and Firebase for the back end, as seen in the MVP documentation we created in the meeting (possibly not pushed by Jasper yet). The documentation also provides info on the different pages that we will need to create (look for each step of the Use Case),

**Comment by jvsluis** [comment]
Clarification:
- Using React to front end
- Switching from bootstrap to tailwind

Full feature description:
Feature name: Initial React App Setup
Description: Create react app skeleton so we can start working on sub tasks
Requires: Use npm to init initial repo and get tailwind setup
Due: Milestone 1.
Status: In-progress.
Time Estimation: 2 hours.
