### ISSUE TITLE
Figma Diagrams

### ISSUE THREAD

**Issue by DH3773** [J-Raymer/printlink3d#2]
The plan for the UI design is for each of us to individually create a UI mockup based on how we imagine the website looking, so that the final design can take the best parts of each individual's design. It would be great if each group member could create a set of Figma UI mockups (very simple ones) for Friday so that Jasper can get working on the cumulative design.

Jasper will be creating a Figma page for the project soon. Make sure that when you do your designs you just create new cells and not new pages, as you need to pay to get more than ~3 pages whereas you can have infinite cells.

**Comment by DH3773** [comment]
They can also be done on just pen and paper, Jasper will create the final mockups on Figma however

**Comment by Jasper-Nelligan** [comment]
Done mine. @DH3773 I merged yours into the main board just because we're limited in the amount of boards we can create

**Comment by mas393** [comment]
Added my sketches to the board

**Comment by jvsluis** [comment]
Added my mockups to the board

**Comment by DH3773** [comment]
All sketches added.
