### ISSUE TITLE
Home page text gets messed up when zooming

### ISSUE THREAD

**Issue by Jasper-Nelligan** [J-Raymer/printlink3d#34]
The "I need printing/I can print" gets messed up when zooming into the home page

**Comment by J-Raymer** [comment]
Tailwind makes responsive design pretty straight forward without the need of media queries.

For example this sets a default width to 16, then increases size based on screen size: 

`<img class="w-16 md:w-32 lg:w-48" src="...">`

Reference:
https://tailwindcss.com/docs/responsive-design

**Comment by Jasper-Nelligan** [comment]
Closing this since we're completely redoing the home page anyway
