### ISSUE TITLE
Profile pages

### ISSUE THREAD

**Issue by J-Raymer** [J-Raymer/printlink3d#55]
We need to design and implement a profile page for users. The profile page will be built with a Profile component and we can have different views depending on 3 use cases: My Profile (viewing your own profile, Printer Profile (viewing another users profile when looking at a print job), Customer Profile (when looking at a profile through a print job from the perspective of a printer looking at a print job)

**My Profile**
viewing your own profile, should include ratings, jobs, messages, and settings

- [ ] Name
- [ ] Username (unique)
- [ ] Profile photo
- [ ] Rating 
- [ ] Messages
- [ ] Settings 
- [ ] Customer Tab/Section
- [ ] List of jobs (New Job card with status, link to printer profile, message option?, ect)
- [ ] Printer Tab/Section
- [ ] List of jobs 

**Printer Profile**
- [ ] Username (unique)
- [ ] Profile Photo (help with trust for local pickup, maybe we can make a profile photo mandatory for local pickup or make it an option when creating a job)
- [ ] Printer Rating (5 star system, show number of ratings)
- [ ] Printer Reviews (title, description, option for photo)
- [ ] Message option

**Customer Profile**
- [ ] Username (unique)
- [ ] Rating (Do we want to include a customer rating? This would improve trust on the printer side and prevent abusive customers)
- [ ] Message option

**Comment by Jasper-Nelligan** [comment]
What do you mean by Printer Tab/Section? In the My Profile list
