### ISSUE TITLE
Customers can upload print jobs

### ISSUE THREAD

**Issue by mas393** [J-Raymer/printlink3d#6]
# Description
With this feature, customers who want something printed will be able to upload an STL file through the app and configure job parameters including:
- printer distance
- infill percentage
- material type

# Requirements
- [x] Figma mockups for pages
- [x] #8 
- [x] #7
- [x] #25
- [x] #26
- [x] Print job confirmation page
- [x] Sending print job details (file & configuration) to DB

**Comment by Jasper-Nelligan** [comment]
Marking as closed as all items have been completed
