### ISSUE TITLE
Fix firebase node modules appearing in parent folder

### ISSUE THREAD

**Issue by Jasper-Nelligan** [J-Raymer/printlink3d#61]
On my device, a node_modules folder would appear in the parent git folder, adding all the firebase files to the commit. As a temporary solution I added a new .gitignore files, however we should investigate why only the firebase modules are being added outside the "app" folder

**Comment by J-Raymer** [comment]
This is probably because the root of the project is outside the "app" folder. Someone probably installed a package at the root by mistake. I will mark this done and restructure the folders
