### ISSUE TITLE
Create order details page

### ISSUE THREAD

**Issue by Jasper-Nelligan** [J-Raymer/printlink3d#65]
This is the page where it shows all job details, status, as well as a chat box for connecting with the customer/printer

**Comment by mas393** [comment]
![Screenshot from 2024-02-29 16-49-05](https://github.com/J-Raymer/printlink3d/assets/44050431/e5eee2f8-4112-4d8a-bda8-40609f3c2c8b)

For reference, the latest mockup which I will be implementing
